openapi: 3.0.3
info:
  title: RAG Chatbot API
  description: API for the Integrated RAG Chatbot for AI-native Textbook
  version: 1.0.0
servers:
  - url: https://api.hackathon-1-giaic.vercel.app
    description: Production server
  - url: https://staging-api.hackathon-1-giaic.vercel.app
    description: Staging server

paths:
  /v1/query:
    post:
      summary: Submit a query to the RAG chatbot
      description: Process a user query against the textbook content with optional selected text context
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid request parameters
        '429':
          description: Rate limit exceeded
        '500':
          description: Internal server error
      security:
        - api_key: []

  /v1/query/stream:
    post:
      summary: Submit a query with streaming response
      description: Process a user query and return response as a stream
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Streaming response from the chatbot
          content:
            text/event-stream:
              schema:
                type: string
        '400':
          description: Invalid request parameters
        '429':
          description: Rate limit exceeded
        '500':
          description: Internal server error
      security:
        - api_key: []

  /v1/health:
    get:
      summary: Health check endpoint
      description: Check the health status of the RAG chatbot service
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    QueryRequest:
      type: object
      required:
        - query
        - mode
      properties:
        query:
          type: string
          description: The user's question or query text
          example: "What is the principle of conservation of momentum?"
        mode:
          type: string
          enum: [FULL_BOOK, SELECTED_TEXT]
          description: The query mode - full book or selected text only
          example: "FULL_BOOK"
        selected_text:
          type: string
          description: Optional text selected by the user for SELECTED_TEXT mode
          example: "The principle of conservation of momentum states that..."
        include_references:
          type: boolean
          description: Whether to include source references in the response
          default: true

    QueryResponse:
      type: object
      required:
        - response
        - references
        - query_id
      properties:
        response:
          type: string
          description: The chatbot's response to the query
          example: "The principle of conservation of momentum states that in an isolated system, the total momentum remains constant..."
        references:
          type: array
          items:
            $ref: '#/components/schemas/Reference'
          description: List of references to textbook sections supporting the response
        query_id:
          type: string
          format: uuid
          description: Unique identifier for the query
          example: "550e8400-e29b-41d4-a716-446655440000"
        confidence_score:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: Confidence score of the response
          example: 0.85

    Reference:
      type: object
      required:
        - source
        - page_number
        - section
      properties:
        source:
          type: string
          description: The textbook source identifier
          example: "physics-textbook-v1"
        page_number:
          type: integer
          description: Page number in the textbook
          example: 142
        section:
          type: string
          description: Section or chapter name
          example: "Chapter 7: Momentum and Collisions"
        text_preview:
          type: string
          description: Preview of the referenced text
          example: "The principle of conservation of momentum states that..."

    HealthResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum: [healthy, degraded, unavailable]
          description: Current health status
          example: "healthy"
        timestamp:
          type: string
          format: date-time
          description: Time of the health check
          example: "2025-12-16T10:00:00Z"
        details:
          type: object
          description: Additional health details
          properties:
            qdrant_connected:
              type: boolean
              description: Whether Qdrant vector store is accessible
            postgres_connected:
              type: boolean
              description: Whether Postgres database is accessible

  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication